; Cross-file para build em CI.

[constants]
triple = 'aarch64-linux-gnu'

[binaries]
c = triple + '-gcc'
ar = triple + '-ar'
strip = triple + '-strip'

[built-in options]
libdir = 'lib' / 'aarch64-unknown-linux-gnu'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
