; Cross-file para build em CI.

[constants]
triple = 'arm-linux-gnueabi'

[binaries]
c = triple + '-gcc'
ar = triple + '-ar'
strip = triple + '-strip'

[built-in options]
libdir = 'lib' / 'arm-unknown-linux-gnueabi'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'
