; Cross-file para build em CI.

[constants]
triple = 'i686-linux-gnu'

[binaries]
c = triple + '-gcc'
ar = triple + '-ar'
strip = triple + '-strip'

[built-in options]
libdir = 'lib' / 'i686-unknown-linux-gnu'

[host_machine]
system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
