; Cross-file para informar libdir e host_machine,
; a mágica real está no vcvarsall.bat usado pelos scripts Python.

[constants]
triple = 'x86_64-pc-windows-msvc'

[binaries]
c = 'cl'
strip = 'dumpbin'

[built-in options]
libdir = 'lib' / triple
vsenv = false

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
