; Cross-file para build em CI.

[constants]
arch = 'x86_64'
triple = arch + '-apple-darwin'

[binaries]
c = 'clang'
ar = 'ar'
strip = 'strip'

[built-in options]
libdir = 'lib'
c_args = ['-target', triple]
c_link_args = c_args

[host_machine]
system = 'darwin'
cpu_family = arch
cpu = arch
endian = 'little'
