name: Distribuição de binários
on:
  # Para teste manual de workflow sem precisar de release.
  workflow_dispatch:
  release:
    types: published

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target:
          - name: linux-gnu
            runs-on: ubuntu-24.04

          - name: pc-windows
            runs-on: windows-2022

          - name: apple-darwin
            runs-on: macos-15-intel

    runs-on: ${{ matrix.target.runs-on }}
    name: Gerando distribuição para ${{ matrix.target.name }}
    steps:
      - if: ${{ matrix.target.name == 'linux-gnu' }}
        name: Atualizando repositórios (linux-gnu)
        run: sudo apt update -y
      - if: ${{ matrix.target.name == 'linux-gnu' }}
        name: Instalando dependências de build (linux-gnu)
        run: >
          sudo apt install -y
          crossbuild-essential-amd64
          crossbuild-essential-i386
          crossbuild-essential-arm64
          crossbuild-essential-armel
          &&
          sudo gem install --no-document fpm
      - if: ${{ matrix.target.name == 'pc-windows' }}
        name:  Instalando dependências de build (pc-windows)
        env:
          MSYSTEM: UCRT64
          MSYS2_PATH_TYPE: inherit
        shell: C:\msys64\usr\bin\bash.exe -l {0}
        run: >
          pacman --noconfirm -S
          mingw-w64-cross-clang
          lld

      - if: ${{ matrix.target.name == 'linux-gnu' }}
        name: Instalando Meson (linux-gnu)
        run: pip3 install --user --break-system-packages meson
      - if: ${{ matrix.target.name == 'pc-windows' }}
        name: Instalando Meson (pc-windows)
        run: pip install meson
      - if: ${{ matrix.target.name == 'apple-darwin' }}
        name: Instalando Meson (apple-darwin)
        run: brew install meson

      - name: Instalando Just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.48.0

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true

      - if: ${{ matrix.target.name == 'pc-windows' }}
        name: Gerando cross-files do Meson para pc-windows-gnu
        run: just config Meson+MSYS

      - name: Realizando build e criando artefatos
        run: just ci dist ${{ matrix.target.name }}

      - name: Fazendo upload dos artefatos
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target.name }}
          path: dist/libtro*

  upload:
    # O upload não entra em testes manuais,
    # se REALMENTE for necessário testar
    # este job, crie uma tag gh-test-<próximo número>
    # e publique a release para testar este job.
    if: ${{ github.event_name == 'release'}}
    name: 'Fazendo upload dos artefatos para o release'
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Pegando os artefatos
        uses: actions/download-artifact@v7
        with:
          path: dist

      - name: Depurar diretório dos artefatos
        run: find dist

      - name: Fazendo upload dos artefatos no release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh release upload
          ${{ github.event.release.tag_name }}
          dist/**/* --clobber
          --repo ${{ github.repository }}
